add_kernel_sources(Assert/)
add_kernel_sources(Error/)
add_kernel_sources(IRQ/)
add_kernel_sources(Log/)
add_kernel_sources(Mem/)
add_kernel_sources(MP/)
add_kernel_sources(Start/)
add_kernel_sources(Task/)
