if(${MU_MACHINE} STREQUAL "x86_64")
    add_kernel_sources(Daemons/)
    add_kernel_sources(Drivers/)
    add_kernel_sources(Kernel/)
    add_kernel_sources(Locks/)
    add_kernel_sources(Memory/)
    add_kernel_sources(Process/)
    add_kernel_sources(Scheduler/)
    add_kernel_sources(Syscalls/)
endif()

add_kernel_sources(Core/)
add_kernel_sources(Structs/)