name: Build & Test LibGeneric

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DMU_BUILD_TYPE=test -DCMAKE_MODULE_PATH=${{github.workspace}}/CMake/ ${{github.workspace}}/Library/LibGeneric/

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target TestLibGeneric

    - name: Test LibGeneric
      run: ${{github.workspace}}/build/TestLibGeneric
