name: Build Kernel

on:
  push:
    branches: [ "master", "gh-presets-ci", "gh-enable-riscv" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - build_preset: x86_64-Debug
            container_image: ghcr.io/muzuwi/muos-toolchain:v3
            x86_iso: True
          - build_preset: x86_64-RelWithDebInfo
            container_image: ghcr.io/muzuwi/muos-toolchain:v3
            x86_iso: True
          - build_preset: x86_64-ExperimentalHacks
            container_image: ghcr.io/muzuwi/muos-toolchain:v3
            x86_iso: True
          - build_preset: starfive-visionfive2
            container_image: ghcr.io/muzuwi/muos-toolchain:v3-rv64
            rv64_uimage: True
          - build_preset: sifive-unmatched-unleashed
            container_image: ghcr.io/muzuwi/muos-toolchain:v3-rv64
            rv64_uimage: True

    container:
      image: ${{ matrix.container_image }}

    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: apt update && apt install -qq -y grub-pc xorriso ninja-build u-boot-tools

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build --preset ${{ matrix.build_preset }}

    - name: Build the project
      run: cmake --build ${{github.workspace}}/build --target all

    - name: Copy emulator run scripts to the output directory
      # NOTE: See https://github.com/actions/runner/issues/2058
      # GITHUB_WORKSPACE points to the repository/sources
      run: |
        cp -r $GITHUB_WORKSPACE/Scripts/* $GITHUB_WORKSPACE/Bin/

    - name: Collect build metadata for artifact stamping
      id: buildmeta
      run: |
        cd $GITHUB_WORKSPACE/
        git config --global --add safe.directory $GITHUB_WORKSPACE
        echo "gitrev=$(git describe --always --dirty)" >> $GITHUB_OUTPUT

    - name: Upload system image and kernel artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MuOS.${{ matrix.build_preset }}.${{ github.ref_name }}.${{ steps.buildmeta.outputs.gitrev }}
        path: |
          ${{github.workspace}}/Bin/*

