name: Build Kernel

on:
  push:
    branches: [ "master", "gh-presets-ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/muzuwi/muos-toolchain:v3
    strategy:
      matrix:
        build_preset: [x86_64-Debug,x86_64-RelWithDebInfo,x86_64-ExperimentalHacks]
    continue-on-error: ${{ startsWith(matrix.build_preset, 'riscv64') }}

    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: apt update && apt install -qq -y grub-pc xorriso ninja-build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build --preset ${{ matrix.build_preset }}

    - name: Build kernel executable
      run: cmake --build ${{github.workspace}}/build --target KernelELF

    - name: Build ISO
      if: ${{ startsWith(matrix.build_preset, 'x86_64') }}
      run: cmake --build ${{github.workspace}}/build --target BootableISO

    - name: Copy emulator run scripts to the output directory
      # NOTE: See https://github.com/actions/runner/issues/2058
      # GITHUB_WORKSPACE points to the repository/sources
      run: |
        cp -r $GITHUB_WORKSPACE/Scripts/* $GITHUB_WORKSPACE/Root/

    - name: Collect build metadata for artifact stamping
      id: buildmeta
      run: |
        cd $GITHUB_WORKSPACE/
        git config --global --add safe.directory $GITHUB_WORKSPACE
        echo "gitrev=$(git describe --always --dirty)" >> $GITHUB_OUTPUT

    - name: Upload system image and kernel artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MuOS.${{ matrix.build_preset }}.${{ github.ref_name }}.${{ steps.buildmeta.outputs.gitrev }}
        path: ${{github.workspace}}/Root/*

