name: Build Kernel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/muzuwi/muos-toolchain:v1

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/local/muOS/bin/x86_64-muos-gcc -DCMAKE_CXX_COMPILER=/usr/local/muOS/bin/x86_64-muos-g++ -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY -DCMAKE_ASM-ATT_COMPILER=/usr/local/muOS/bin/x86_64-muos-as -DCMAKE_INSTALL_PREFIX=/usr/local/muOS

    - name: Build
      run: cmake --build ${{github.workspace}}/build     
