name: Build and run library tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt update && sudo apt install -qq -y grub-pc xorriso ninja-build u-boot-tools

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build --preset host-libtest

    - name: Build project
      run: cmake --build ${{github.workspace}}/build

    - name: Run library tests
      run: env -C ${{github.workspace}}/build ctest
